/* WITH절은 서브쿼리를 만들고 재사용 가능한 공통 테이블 표현식(Common Table Expression, CTE)을 정의하는 방법이다. */
WITH TOTAL_JULY AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_JULY_ORDER FROM JULY GROUP BY FLAVOR
)

SELECT FH.FLAVOR FROM FIRST_HALF AS FH JOIN TOTAL_JULY AS J ON FH.FLAVOR = J.FLAVOR ORDER BY FH.TOTAL_ORDER + J.TOTAL_JULY_ORDER DESC LIMIT 3;